# Generated by Django 5.2 on 2025-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipiec',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
