# Generated by Django 5.2 on 2025-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiec', '0002_alter_recipiec_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipiec',
            name='cooking_time',
            field=models.TimeField(null=True),
        ),
    ]
