# Generated by Django 5.2 on 2025-04-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiec', '0004_alter_recipiec_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipiec',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Время в минутах', null=True),
        ),
    ]
