# Generated by Django 5.2 on 2025-04-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipiec', '0005_alter_recipiec_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Desks',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
