# Generated by Django 5.2 on 2025-04-06 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiec', '0006_remove_favourites_desk_remove_rating_recipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipiec',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сохранен пользователем'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipiec.recipiec', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='count',
            field=models.CharField(max_length=128, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipiec.recipiec', verbose_name='Для рецепта'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='category',
            field=models.ManyToManyField(to='recipiec.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Время в минутах', null=True, verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='count_views',
            field=models.PositiveIntegerField(verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='recipiec',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
